# Generated by Django 3.2.2 on 2021-05-16 11:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fillim_leje', models.DateTimeField(auto_now_add=True)),
                ('fund_leje', models.DateTimeField(default=datetime.timedelta(seconds=14400))),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_id', to='employee.employee')),
            ],
        ),
    ]
