# Generated by Django 3.2.2 on 2021-05-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leje',
            name='fund_leje',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
