# Generated by Django 3.2.2 on 2021-05-27 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_approvimleje'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApprovimLeje',
        ),
    ]
