# Generated by Django 3.2.2 on 2021-05-27 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave', '0007_delete_approvimleje'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovimLeje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('koment', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('leje', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leje_set', to='leave.leje')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
