# Generated by Django 3.2.2 on 2021-05-28 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_approvimleje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvimleje',
            name='id',
        ),
        migrations.AlterField(
            model_name='approvimleje',
            name='leje',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='leje_set', serialize=False, to='leave.leje'),
        ),
    ]
