# Generated by Django 3.2.2 on 2021-05-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0009_auto_20210528_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvimleje',
            name='status',
            field=models.BooleanField(),
        ),
    ]
