# Generated by Django 3.2.2 on 2021-05-16 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='e_user', serialize=False, to='auth.user')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_department', to='department.department')),
            ],
        ),
    ]
