# Generated by Django 3.2.2 on 2021-06-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_rename_user_id_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='annual_days',
            field=models.FloatField(default=20),
        ),
    ]
